kartanu/backoffice/urls.py
from django.urls import path, include
from .views import (
    login_view, log_out, users, add_user, 
    import_user, print_card, print_view,
    mark_as_print, user_preview, add_to_print,
    dashboard
)

app_name = "backoffice"
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('user', users, name='users'),
    path('<int:id>/preview/', user_preview, name='user_preview'),
    path('<int:id>/add-to-print/', add_to_print, name='add_to_print'),
    path('login/', login_view, name='login'),
    path('log-out/', log_out, name='log_out'),
    path('add-user/', add_user, name='add_user'),
    path('import-user/', import_user, name='import_user'),
    path('print-view/', print_view, name='print_view'),
    path('print-card/', print_card, name='print_card'),
    path('mark-as-print/', mark_as_print, name='mark_as_print'),
]

kartanu/frontend/urls.py
# from django.urls import path
# from .views import *

# app_name = "frontend"
# urlpatterns = [
#     path('', index, name='index'),
#     path('post-formulir/', post_formulir, name='post_formulir'),
# ]

kartanu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from kartanu.apps.kecamatan.models import Kecamatan
from kartanu.apps.kelurahan.models import Kelurahan
from kartanu.backoffice.autocomplete import (
    KecamatanAutocomplete,
    KelurahanAutocomplete
)


admin.site.site_header = "kartanu Admin"
admin.site.site_title = "kartanu Admin Portal"
admin.site.index_title = "Welcome to kartanu Admin Portal"

urlpatterns = [
    path('kartanu-admin/', admin.site.urls),
    path('', include('kartanu.backoffice.urls', namespace='backoffice')),
    url("kecamatan-autocomplete/$", KecamatanAutocomplete.as_view(model=Kecamatan),
        name='kecamatan-autocomplete',),
    url("kelurahana-utocomplete/$", KelurahanAutocomplete.as_view(model=Kelurahan),
        name='kelurahan-autocomplete',),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

kartanu/apps/kabupaten/models.py
from django.db import models

# Create your models here.


class Kabupaten(models.Model):
    code = models.IntegerField(null=True, default=0)
    name = models.CharField(max_length=50)
    provinsi = models.ForeignKey('provinsi.Provinsi', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

kartanu/apps/kecamatan/models.py
from django.db import models


class Kecamatan(models.Model):
    name = models.CharField(max_length=254)
    code = models.IntegerField(null=True, default=0)
    kabupaten = models.ForeignKey('kabupaten.Kabupaten', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

kartanu/apps/user/models.py
import random
import string
from datetime import datetime, timedelta

from django.apps.registry import apps
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone
from kartanu.core.utils import FilenameGenerator
from kartanu.core.middleware import get_kecamatan_id, check_is_superuser, is_login
from kartanu.apps.kabupaten.models import Kabupaten
from kartanu.apps.provinsi.models import Provinsi

from model_utils import Choices
from sequences import get_next_value


class CustomUserManager(UserManager):
    def create_user(self, username, password, **extra_fields):
        now = timezone.now()
        user = self.model(
            username=username,
            is_active=True, is_superuser=False,
            last_login=now, date_joined=now, **extra_fields)

        if password:
            user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, password, **extra_fields):
        user = self.create_user(username, password, **extra_fields)
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=50, null=True)
    mother_name = models.CharField(max_length=50, null=True)
    nik = models.CharField(max_length=50, unique=True, null=True)
    email = models.EmailField(null=True, blank=True, max_length=50, db_index=True, default=None)
    is_active = models.BooleanField('active', default=True)
    is_staff = models.BooleanField('Status Staff', default=False)
    provinsi = models.ForeignKey(
        'provinsi.Provinsi', on_delete=models.PROTECT, blank=True, null=True)
    kabupaten = models.ForeignKey(
        'kabupaten.Kabupaten', on_delete=models.PROTECT, blank=True, null=True)
    kecamatan = models.ForeignKey(
        'kecamatan.Kecamatan', on_delete=models.PROTECT, null=True)
    kelurahan = models.ForeignKey(
        'kelurahan.Kelurahan', on_delete=models.PROTECT, null=True)
    rt = models.CharField(max_length=50, blank=True, null=True)
    rw = models.CharField(max_length=50, blank=True, null=True)
    mobile_number = models.CharField(max_length=30, default='', blank=True)
    picture = models.ImageField(upload_to=FilenameGenerator(prefix='user'), default='', blank=True)
    ktp = models.ImageField(upload_to=FilenameGenerator(prefix='user'), default='', blank=True)
    place_of_birth = models.CharField(max_length=50, unique=True, null=True)
    from_web = models.BooleanField(default=False)
    dob = models.DateField(blank=True, null=True)
    GENDER = Choices(("L", "Laki Laki"), ("P", "Perempuan"))
    gender = models.CharField(
        max_length=10, choices=GENDER)
    MARITAL_STATUS = Choices(("Kawin", "Kawin"), ("Lajang", "Lajang"))
    marital_status = models.CharField(
        max_length=10, choices=MARITAL_STATUS, default="Lajang")
    job = models.CharField(max_length=20, blank=True, null=True)
    EDUCATION = Choices(
        ("SD", "SD"),
        ("SMP", "SMP"),
        ("SLTP", "SLTP"),
        ("SMA", "SMA"),
        ("SLTA", "SLTA"),
        ("D3", "D3"),
        ("S1", "S1"),
        ("S2", "S2"),
        ("S3", "S3"),
        ("Lainnya", "Lainnya")
    )
    education = models.CharField(max_length=255, blank=True, null=True, choices=EDUCATION)
    id_card_number = models.CharField(max_length=25, blank=True, null=True)
    order = models.IntegerField(default=0, blank=True)
    print_counter = models.IntegerField(default=0)

    USERNAME_FIELD = 'username'
    objects = CustomUserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return '%s - %s' % (self.username, self.name)

    def __unicode__(self):
        return self.name or self.username or self.email or 'User #%d' % (self.id)

    def save(self, *args, **kwargs):
        exist_id = self.id
        super(User, self).save(*args, **kwargs)
        self.kabupaten = Kabupaten.objects.first()
        self.provinsi = Provinsi.objects.first()
        if not exist_id:
            self.order = get_next_value("order_user")
            last_counter = get_next_value(self.kelurahan.code) + 1
            self.id_card_number = f"{self.kelurahan.code}-{str(last_counter).zfill(5)}"
            PrintCard.objects.create(user=self, order=self.order)
            self.save()


class PrintCard(models.Model):
    user = models.ForeignKey(
        'user.User', on_delete=models.CASCADE, unique=True)
    order = models.IntegerField(default=0)

kartanu/apps/user/views.py
from django.shortcuts import render

# Create your views here.

kartanu/backoffice/views.py
import csv, io, os
from django.core.files import File
from django.apps.registry import apps
from django.contrib import messages
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from kartanu.apps.user.models import User, PrintCard
from kartanu.apps.kecamatan.models import Kecamatan
from kartanu.apps.kelurahan.models import Kelurahan
from kartanu.apps.user.decorators import login_validate
from kartanu.backoffice.forms import LoginForm, UserCreateForm
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.urls import reverse
from django.db import transaction
from django.http import JsonResponse
from datetime import date


get_model = apps.get_model

def login_view(request):
    auth_form = LoginForm(data=request.POST or None)
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        auth_form.get_user()
        return redirect("backoffice:dashboard")
    else:
        messages.error(request, "Username and Password are incorrect")

    list(messages.get_messages(request))
    context = dict(auth_form=auth_form,)
    return TemplateResponse(request, "backoffice/login.html", context)


def log_out(request):
    logout(request)
    return redirect("backoffice:login")


@login_validate
def dashboard(request):
    users = User.objects.all().exclude(is_superuser=True).exclude(is_staff=True)
    context = dict(
        to_print = users.filter(print_counter=0).count(),
        users_count = users.count(),
        already_printed= users.filter(print_counter__gt=0).count(),
    )
    return TemplateResponse(request, "backoffice/index.html", context)

@login_validate
def users(request):
    users = User.objects.all().order_by("id").exclude(is_superuser=True).exclude(is_staff=True)

    if not request.user.is_superuser:
        users = users.filter(kecamatan=request.user.kecamatan)

    page = request.GET.get("page")
    search = request.GET.get("search", "")
    
    if search:
        users = users.filter(Q(name__icontains=search) | Q(nik__icontains=search))
    
    counter = request.GET.get("counter", "")
    if counter:
        users = users.filter(print_counter=int(counter))

    results_per_page = 30
   
    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "Users",
        "filter": {"search": search, "counter": counter},
    }
    return TemplateResponse(request, "backoffice/users.html", context)


@login_validate
def user_preview(request, id):
    user = User.objects.all().get(id=id)
    context = {
        "user": user,
    }
    return TemplateResponse(request, "backoffice/user-detail.html", context)


def add_to_print(request, id):
    user = User.objects.all().get(id=id)
    PrintCard.objects.update_or_create(user=user, order=user.order)
    return JsonResponse({"status": "OK"}, safe=False)


@login_validate
def add_user(request):
    kecamatan=request.user.kecamatan
    form = UserCreateForm(request.POST or None, request.FILES or None, 
        initial={'kecamatan': kecamatan})
    
    if form.is_valid():
        form.save()
        messages.success(request, 'success')
        return redirect(reverse('backoffice:users'))
    else:
        print(form.errors)

    context = dict(
        edit=False,
        form=form,
        title='Add User'
    )
    return TemplateResponse(request, 'backoffice/add-user.html', context)



@login_validate
@transaction.atomic
def import_user(request):
    context = {
        'order': 'Order of the CSV should be no, name, nik, gender, profile picture, ktp picture, place of birth, date of birth, rt, rw, desa, kecamatan, marital status, formal education, job, mobile_number, email'
    }

    if request.method == "POST":
        folder_name = request.POST.get('folder-name')
        csv_file = request.FILES.get('csv')
        data_set = csv_file.read().decode('UTF-8')
        io_string = io.StringIO(data_set)
        next(io_string)

        with transaction.atomic():
            line = 0
            try:
                for column in csv.reader(io_string, delimiter=';', quotechar="|"):
                    if not column[1]:
                        continue

                    line = line + 1
                
                    kecamatan = Kecamatan.objects.filter(name=column[11].strip()).first()
                    if not kecamatan:
                        raise Exception(f'{column[11]} Kecamatan not found')

                    kelurahan = Kelurahan.objects.filter(name=column[10].strip()).first()
                    if not kelurahan:
                        raise Exception(f'{column[10]} Kelurahan not found')

                    ktp = f'./to_upload/{folder_name}/{column[5]}.jpeg'
                    if not os.path.isfile(ktp):
                        raise Exception(f'KTP picture not found')

                    picture = f'./to_upload/{folder_name}/{column[4]}.jpeg'
                    if not os.path.isfile(picture):
                        raise Exception(f'Profile picture not found')

                    nik = column[2].replace("'", "").replace("`", "")
                    
                    user, created = User.objects.update_or_create(
                        nik=nik,
                        defaults={
                            'username': nik, 
                            'name': column[1], 
                            'gender': column[3], 
                            # profile 4
                            # ktp 5
                            'place_of_birth': column[6], 
                            'dob': column[7], 
                            'rt': column[8],
                            'rw': column[9],
                            'kelurahan': kelurahan, #10
                            'kecamatan': kecamatan, #11
                            'marital_status': column[12],
                            'education': column[13],
                            'job': column[14],
                            'mobile_number': column[15],
                            'email': column[16],
                            # 'mother_name': column[11],
                        }
                    )

                    ktp = open(ktp, 'rb')
                    ktp = File(ktp)
                    user.ktp.save(column[9], ktp)
                    ktp.close()

                    picture = open(picture, 'rb')
                    picture = File(picture)
                    user.picture.save(column[10], picture)
                    picture.close()


                context['success'] = "Data Berhasil Di Import"
            except IndexError as e:
                context['error'] = f"{e}. Line: {line}" 
                transaction.set_rollback(True)
            except Exception as e:
                context['error'] = f"{e}. Line: {line}"
                transaction.set_rollback(True)

        return TemplateResponse(request, 'backoffice/import.html', context)

    return TemplateResponse(request, 'backoffice/import.html', context)



@login_validate
def print_view(request):
    users = PrintCard.objects.all().select_related('user').order_by('order')
    page = request.GET.get("page")
    # search = request.GET.get("search", "")
    # if search:
    #     serials = serials.filter(serial_number=search)

    # status = request.GET.get("status")
    # if status:
    #     serials = serials.filter(status=status)

    # type = request.GET.get("type")
    # if type:
    #     serials = serials.filter(type=type)

    # action = request.GET.get("action")
    # if action == 'export':
    #     response = HttpResponse(
    #         content_type='text/csv',
    #         # headers={'Content-Disposition': 'attachment; filename="qrcode.csv"'},
    #     )
    #     writer = csv.writer(response)
    #     writer.writerow(['No', 'Qr-Code', 'Status'])
    #     idx = 0
    #     for sr in serials:
    #         idx += 1
    #         writer.writerow([idx, sr.serial_number, sr.status])
    #     return response
    results_per_page = 30
    # new_count = serials.filter(status="new").count()
    # redeem_count = serials.filter(status="redeem").count()

    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "Print Card",
        # "filter": {"search": search, "status": status, "type": type},
    }

    return TemplateResponse(request, "backoffice/print-view.html", context)


@login_validate
def print_card(request):
    users = PrintCard.objects.all().select_related('user').order_by('order')
    start = request.GET.get("start", 0)
    end = request.GET.get("end", 0)
    users = users.filter(order__gte=start).filter(order__lte=end)


    context = {
        "users": users,
        "title": "Print Card",
        "date": date.today()
    }
    return TemplateResponse(request, 'backoffice/print-card.html', context)


@login_validate
def mark_as_print(request):
    prints = PrintCard.objects.all().select_related('user').order_by('order')
    if (request.POST):
        start = request.POST.get("start", 0)
        end = request.POST.get("end", 0)
        prints = prints.filter(order__gte=start).filter(order__lte=end)
        for prin in prints:
            prin.user.print_counter = prin.user.print_counter + 1
            prin.user.save()
        prints.delete()
        return redirect(reverse('backoffice:print_view'))

    # context = {
    #     "users": prints,
    #     "title": "Print Card",
    # }
    # return redirect(reverse('backoffice:users'))

kartanu/templates/backoffice/print-view.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% load qr_tags %}
{% load templatehelpers %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
<div class="box" id="content">
  <div class="box-inner">
    <!-- <div class="box-title">
      <h2>Print View</h2>
    </div> -->

    <div class="box-title">
      <div class="row">
        <div class="col-md-6">
          <label>PRINT</label>
          <form method="GET" action="{% url 'backoffice:print_card' %}" target="print_popup" id="form1">
            <div class="row">
              <div class="col-sm-4" ;>
                <div class="input-group">
                  <input type="number" name="start" class="form-control" id="start" placeholder="Start">
                </div>
              </div>

              <div class="col-sm-4" ;>
                <div class="input-group">
                  <input type="number" name="end" class="form-control" id="end" placeholder="End">
                </div>
              </div>

              <div class="col-sm-4" style="text-align: left;">
                <button type="submit" id="btn-search-fix-h" class="btn btn-primary" onclick="return validate();">
                  PRINT
                </button>
              </div>
            </div>
          </form>
        </div>
        <div class="col-md-6">
          <label>MARK AS PRINTED</label>
          <form method="POST" action="{% url 'backoffice:mark_as_print' %}" id="form2">
            {% csrf_token %}
            <div class="row">
              <div class="col-sm-4" ;>
                <div class="input-group">
                  <input type="number" name="start" class="form-control" id="start2" placeholder="Start" required>
                </div>
              </div>

              <div class="col-sm-4" ;>
                <div class="input-group">
                  <input type="number" name="end" class="form-control" id="end2" placeholder="End" required>
                </div>
              </div>

              <div class="col-sm-4" style="text-align: left;">
                <button type="submit" id="btn-search-fix-h" class="btn btn-primary" onclick="return validate2()">
                  MARK AS PRINT
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Print Order</th>
          <th>Name</th>
          <th>Card Number</th>
          <th>Kecamatan</th>
          <th>Kelurahan</th>
        </tr>
      </thead>
      <tbody>
        {% for us in users %}
        <tr>
          <th scope="row">{{us.user.order}}</th>
          <td>{{ us.user.name }}</td>
          <td>{{ us.user.id_card_number }}</td>
          <td>{{ us.user.kecamatan }}</td>
          <td>{{ us.user.kelurahan }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


    <div class="pull-right">
      <p>Page {{ users.number }} of {{ users.paginator.num_pages }}</p>
      <nav aria-label="">
        <ul class="pagination">
          {% if users.has_previous %}
          <li class="page-item"><a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a>
          </li>
          <li class="page-item"><a class="page-link"
              href="{% relative_url users.previous_page_number 'page' request.GET.urlencode %}">Previous</a>
          </li>
          {% endif %}
          <!-- {% for i in users.paginator.page_range %}
          <li class="page-item"><a class="page-link {% if users.number == i %}is-active{% endif %}"
              href="{% relative_url i 'page' request.GET.urlencode %}">{{forloop.counter}}</a></li>
          {% endfor %} -->
          {% if users.has_next %}
          <li class="page-item"><a class="page-link"
              href="{% relative_url users.next_page_number 'page' request.GET.urlencode %}">Next</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>

</div>
{% endblock %}

{% block script %}
{% csrf_token %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
  function validate() {
    var min = parseInt(document.getElementById('start').value);
    var max = parseInt(document.getElementById('end').value);
    if (min > max) {
      alert('End must greter than start');
      return false;
    }
  }

   function validate2() {
    var min = parseInt(document.getElementById('start2').value);
    var max = parseInt(document.getElementById('end2').value);
    if (min > max) {
      alert('End must greter than start');
      return false;
    }
  }

</script>
{% endblock %}

kartanu/templates/backoffice/user-detail.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
<div class="box margin-top-profile">
  <div class="profile__content">
    <div class="profile__bio">
      <div class="my-sep1">
        <span>
          {{ user.position }}
        </span>
      </div>
      <h3 class="profile__name">{{ user.name }}</h3>
      <p>{{ user.id_card_number }}</p>
      <hr>
      <div class="overview align-left">
        <div class="row">
          <div class="col-sm-6">
            <ul>
              <li><strong>NIK</strong><span>{{ user.nik | default:'-'}}</span></li>
              <li><strong>Mobile Number</strong><span>{{ user.mobile_number | default:'-' }}</span></li>
              <!-- <li><strong>Wilayah</strong><span>{{ user.region_type | default:'-' }}</span></li> -->
              <!-- <li><strong>Provinsi</strong><span>{{ user.province | default:'-' }}</span></li>
              <li><strong>Kabupaten</strong><span>{{ user.kabupaten | default:'-' }}</span></li> -->
              <li><strong>Kecamatan</strong><span>{{ user.kecamatan | default:'-' }}</span></li>
              <li><strong>Kelurahan</strong><span>{{ user.kelurahan | default:'-' }}</span></li>
              <li><strong>RT / RW</strong><span>{{ user.rt | default:'-' }} / {{ user.rw | default:'-' }}</span></li>
            </ul>
          </div>
          <div class="col-sm-6">
              <ul>
                <li><strong>Jenis Kelamin</strong><span>{{ user.get_gender_display | default:'-' }}</span></li>
                <li><strong>Foto KTP</strong><span>{% if user.ktp %}<a href="{{ user.ktp.url }}" target="_blank">Klik Link</a>{% else %}Foto KTP belum di masukan{% endif %}</li>
                <li><strong>Foto Profil</strong><span>{% if user.picture %}<a href="{{ user.picture.url}}" target="_blank">Klik Link</a>{% else %}Foto KTP belum di masukan{% endif %}</li>
                <li><strong>Print Counter</strong><span>{{ user.print_counter  }}</span></li>
                <li><strong>Email</strong><span>{{ email.print_counter  }}</span></li>
              </ul>
            </div>  
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

kartanu/templates/backoffice/users.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% load templatehelpers %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
<div class="box" id="content">
  <div class="box-inner">
    <div class="box-title">
      <h2>User</h2>
    </div>
    <div class="box-title">
      <form method="GET" action="">
        <div class="row">
          <div class="col-sm-3">
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="Name / NIK"
                value="{{ filter.search }}">
            </div>
          </div>

          <div class="col-sm-2">
            <div class="input-group">
              <input type="text" name="counter" class="form-control" placeholder="Print Counter"
                value="{{ filter.counter }}">
            </div>
          </div>

          <div class="col-sm-2">
            <button type="submit" id="btn-search-fix-h" class="btn btn-primary">
              Submit
            </button>
          </div>

          <div class="col-sm-3">
            <a href="{% url 'backoffice:add_user'%}" class="btn btn-primary">Add User</a>
          </div>

        </div>
      </form>
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Kecamatan</th>
          <th>Kelurahan</th>
          <th>Order</th>
          <th>Print Counter</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <th scope="row"><a class="link" href="{% url 'backoffice:user_preview' user.id %}"> {{ user.id }} </a></th>
          <td><a class="link" href="{% url 'backoffice:user_preview' user.id %}"> {{ user.name }} </a></td>
          <td>{{ user.kecamatan }}</td>
          <td>{{ user.kelurahan }}</td>
          <th>{{ user.order }}</th>
          <td>{{ user.print_counter }}</td>
          <td>
            <button onclick=add_to_print("{% url 'backoffice:add_to_print' user.id %}") class="btn btn-primary">Re
              Print</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- <div class="pull-right">
        <nav aria-label="">
          <ul class="pagination">
            {% if formulirs.has_previous %}
              <li class="page-item"><a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a></li>
              <li class="page-item"><a class="page-link" href="{% relative_url formulirs.previous_page_number 'page' request.GET.urlencode %}">Previous</a></li>
            {% endif %}
            {% for i in formulirs.paginator.page_range %}
              <li class="page-item"><a class="page-link {% if formulirs.number == i %}is-active{% endif %}" href="{% relative_url i 'page' request.GET.urlencode %}">{{forloop.counter}}</a></li>
            {% endfor %}
            {% if formulirs.has_next %}
              <li class="page-item"><a class="page-link" href="{% relative_url formulirs.next_page_number 'page' request.GET.urlencode %}">Next</a></li>
            {% endif %}
          </ul>
        </nav>
      </div> -->

    <div class="pull-right">
      <p>Page {{ formulirs.number }} of {{ formulirs.paginator.num_pages }}</p>
      <nav aria-label="">
        <ul class="pagination">
          {% if formulirs.has_previous %}
          <li class="page-item"><a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a>
          </li>
          <li class="page-item"><a class="page-link"
              href="{% relative_url formulirs.previous_page_number 'page' request.GET.urlencode %}">Previous</a></li>
          {% endif %}
          <!-- {% for i in formulirs.paginator.page_range %}
            <li class="page-item"><a class="page-link {% if formulirs.number == i %}is-active{% endif %}"
                href="{% relative_url i 'page' request.GET.urlencode %}">{{forloop.counter}}</a></li>
            {% endfor %} -->
          {% if formulirs.has_next %}
          <li class="page-item"><a class="page-link"
              href="{% relative_url formulirs.next_page_number 'page' request.GET.urlencode %}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>

</div>
{% endblock %}

{% block script %}
{% csrf_token %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript">
  // $(function () {
  //   $('[data-toggle="tooltip"]').tooltip()
  // })
  // (function ($) {
  //   $('#form2').on('submit', function (e) {
  //     $("#content").loading({
  //       stoppable: true
  //     });
  //     e.preventDefault();
  //     var form = $(this);
  //     var url = form.attr('action');
  //     const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  //     const button = $("#btn_clicked").val();
  //     if (button === 'print') {
  //       $.ajax({
  //         type: 'post',
  //         url: url,
  //         data: form.serialize(),
  //         headers: {
  //           'X-CSRFToken': csrftoken
  //         },
  //         success: function (data) {
  //           console.log(data)
  //           window.location.reload();
  //           $('#content').loading('stop');
  //         },
  //         error: function (xhr, status, error) {
  //           console.log(xhr, status, error)
  //           $('#content').loading('stop');
  //           alert("something went wrong")
  //         }
  //       });
  //     }
  //   })
  // }(jQuery));
  function add_to_print(url) {
    $("#content").loading({stoppable: true});
    var form = $(this);
    $.ajax({
      type: 'get',
      url: url,
      success: function (data) {
        $('#content').loading('stop');
        console.log(data)
        alert("success add to print queue")
      },
      error: function (xhr, status, error) {
        console.log(xhr, status, error)
        $('#content').loading('stop');
        alert("something went wrong")
      }
    });
  }

</script>
{% endblock %}